version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-9

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "9000:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laraveluserpass
        volumes:
            - mysql_data:/var/lib/mysql
        networks: 
            - laravel-9
        ports:
            - "3308:3306"  # Mapeia a porta 3308 no host para a porta 3306 no container


volumes:
    mysql_data:

networks:
    laravel-9:
        driver: bridge
