version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9
networks:
    laravel-9:
        driver: bridge
